travis:
  secure:
    BINSTAR_TOKEN: DuG0O44DK4SZ7X5ZOAvtS+SPsiUIEgbrzp79sbbR63ik9FNTIUlM7KHzK/S+MQCfJM1NJNWd4zJM2tq7JIedRX3usXMp0yEfk8MT/YV6oVTmhASvTijVMFIX9D37Ochodnn4J4UHQJE0iVeenOx0kCpfxpsCzFo6ua0IoPAsdzYq3BoqVi103Vt2jW3VqT24b5wsLOV2gGgVkdMb7B0TpQ3g4VGp/f3xFIHSbDLwJIF/aCtmUsIpnuqHUWapw7NkXgeUkqTVHg1qbG0Wz7i4mbfso93Kb/uBJGRZ4S1yDt2KZ9S+koRQkfJYEt4WAInt5byRTBIyzedS5udZj+k3jIrKKSHlQ1pBnYoU+axfxKO2XoBlqPlqmmRL5BsXToeOJb217nB8MBhh6pzO09qx3mMfCxXOkQyX6ctH5Z2uQ7PZj0ftBpl02tq8xfMOakceRHNjzOMEKRywd360eX65Q7XFCgKU+Sj68HJBeMBzPR+5UpKNTMXjsMV+S/4OYssH15p/x/+YjrdRhgYbn1yqHtLcK/AMuJPi86aLwhHreOIyKX9sRkDNJ2HgvhCu6BVKPEQuJNZ2tIxZ94bPsNfbroO+yeb1yJde0GsgCq8qp4gdq/NX5fsGD9B6RFcM21obhwtXMaT3knO4mCWf9fC7swulUnASIgToEb3WVchlW/g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
