travis:
  secure:
    BINSTAR_TOKEN: r3CK9O4Tv53zNGLMxvzOvIIRqM01E2bEzaXcj9dWGSJgvMM7bn3FLoGbSt26i3GelkgzKIo5lzWK2NZOZcigDQWZ8RuwQ1kAS8kE5FPZhKNv5zs01cltwnt4ILQ1qRpNc4h4o/gBO8oSnruyOiy17DVLJKMYqAB36uiSjy/POL9gR/3/+V7SQs+Nw2HTkAi5ALzJjeqJFFWLGAdJHbish7415TfgrtgB4vJyahbRIC/3tWAc/EpggErdlsYW001wUf4k2ipnCntinEbNjMk5/BvihPEkWoZ2Vz+XP5SvnzSAcS4Dz22APMr2mPdRfhQcJXxRacB9iBy6HIwQJ4UwzfSqiWlkSCvVf6AZzx7SsCx2z5RX7SnkkqDfesTOVAN47K3p3PDoAGXTydhNVGN0Xrvx/pY6/iWynTyviD8yAURwaPFcSZSbwwM1aDxkcOgMlMMeOmssaSnOVe3jfP9B9H0TMMS/KfycFNW2umpGhjppAI2diAphhukLPcIxwohg92JWeM03YMyGNYVpxtm3fohgyzDvFb4lQEoziRxNVcBqopNgHKQ1/NjTpfU3BCzlgAleCHCzR/W7sKTdk1xvpfPp9sx7WzPVj6/6MPv+wGCWYQT8dEgYgEEBqZtNHQEboSWJoc/2bOixhfYJV3muFwKO/F66q3Geekcd9uEfKig=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
